MODEL:
  META_ARCHITECTURE: "PointsCollection"
  MASK_ON: True
  BACKBONE:
    NAME: "build_points_collection_resnet_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEFORM_ON_PER_STAGE: [False, True, True, True] # on Res3,Res4,Res5
    DEFORM_MODULATED: False

DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 32
  BASE_LR: 0.004
  STEPS: (60000, 80000)
  MAX_ITER: 90000
VERSION: 2
