_BASE_: "Base-PointsCollection.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  BASE_LR: 0.002
  STEPS: (120000, 160000)
  MAX_ITER: 180000
INPUT:
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: [0.95,0.95]
