_BASE_: "Base-PointsCollection.yaml"
MODEL:
  BACKBONE:
    NAME: "build_points_collection_vgg_backbone"
  WEIGHTS: "./tools/vgg16_d2.pkl"
  VGG:
    DEPTH: 16
SOLVER:
  BASE_LR: 0.002
  STEPS: (120000, 160000)
  MAX_ITER: 180000
