_BASE_: "Base-PointsCollection.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
SOLVER:
  BASE_LR: 0.002
  STEPS: (120000, 160000)
  MAX_ITER: 180000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  CROP:
    ENABLED: False
    TYPE: "relative_range"
    SIZE: [0.95,0.95]
