_BASE_: "Base-PointsCollection.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
SOLVER:
  BASE_LR: 0.002
  IMS_PER_BATCH: 8
  STEPS: (120000, 160000)
  MAX_ITER: 180000
