_BASE_: "../../../Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_conl_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 50
    NORM: "FrozenBN"  # for more
