_BASE_: Base-CoNL-RCNN-C4.yaml
MODEL:
  CONL:
    STAGES: ['res4']
    BLOCKS: [[-1,],]
    RATIO :  0.25
    DOWNSAMPLE: False
    USE_GN: False
    LR_MULT: 0
    USE_OUT: False
    OUT_BN: False
    WHITEN_TYPE: ['norm']
    TEMP :  1.0
    WITH_GC: False
    WITH_2FC: False
    DOUBLE_CONV: False
    WITH_STATE: True
    NCLS: 8
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  STEPS: (60000, 80000)
  MAX_ITER: 90000


